name: push
on:
  workflow_dispatch:
  push:

env:
  FORGEJO_HOST: git.mpluta.dev

jobs:
  lint:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: https://git.mpluta.dev/mikey/actions/set-up-ssh@main
        with:
          git-host: ${{ env.FORGEJO_HOST }}
          ssh-key: ${{ secrets.SECRETS_REPOSITORY_PRIVATE_KEY }}
          git-hostkey: ${{ secrets.GIT_HOSTKEY }}
      - run: git config --global --add safe.directory "${PWD}"
      - run: nix flake check --accept-flake-config

  generate-readme:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        uses: https://git.mpluta.dev/mikey/actions/set-up-ssh@main
        with:
          git-host: ${{ env.FORGEJO_HOST }}
          ssh-key: ${{ secrets.SECRETS_REPOSITORY_PRIVATE_KEY }}
          git-hostkey: ${{ secrets.GIT_HOSTKEY }}
      - run: mkdir newreadme
      - run: (grep -B 99999 "BEGIN SERVICE LIST" README.md && nix eval --offline --raw --file bin/generateServicesTable.nix && grep -A 99999 "END SERVICE LIST" README.md) > newreadme/README.md
      - uses: actions/upload-artifact@v3
        with:
          name: new-readme
          path: newreadme

  push-readme:
    runs-on: nix
    needs:
      - lint
      - generate-readme
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: new-readme
          path: newreadme
      - run: mv newreadme/README.md README.md
      - name: Commit and push README
        run: |
          git config user.name forgejo-actions
          git config user.email forgejo@git.mpluta.dev
          git add README.md
          git diff-index --quiet HEAD || git commit -m "chore: Generate README.md"
          git push
